AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'read message from sns'
Resources:
  readFromSns:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: read_from_sns.lambda_handler
      Runtime: python2.7
      Description: 'read event from sns'
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::XXXXXXXXXXX:role/Lambda'
      Environment: